author: DomanoSV
description: Flatlands world generator.
name: ${project.name}
version: ${version}-${timestamp}
main: net.dkebnh.bukkit.FlatlandsBuilder.FlatlandsBuilder
load: STARTUP
url: http://www.dkebnh.net/
commands:
    flb:
        description: Informs player of FlatlandsBuilder version.
        usage: /flb help for more information.
        aliases: [fb, flatlandsbuilder]
api-version: 1.13
